
import { OrderType, OrderStatus, Role, User, Zone, Order } from './types';

export const APP_NAME = "مشاوير دمنهور";
export const CURRENCY = "EGP";

export const FLAT_RATES: Record<string, number> = {
  [OrderType.SHOPPING]: 15,
  [OrderType.EMERGENCY]: 25,
  [OrderType.PICK_DROP]: 15,
};

export const SUPPORT_PHONES = [
    "01015259314",
    "01060901989",
    "01001817673"
];

export const HQ_ADDRESS = "دمنهور - شارع عبد السلام الشاذلي بجوار نقابة الأطباء";

export const INITIAL_ZONES: Zone[] = [
  { id: 'zone-1', name: 'بوابة سيدي عدس', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-2', name: 'الصرف', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-3', name: 'مديرية الأمن الجديدة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-4', name: 'مديرية الأمن القديمة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-5', name: 'منطقة الروضة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-6', name: 'المعهد الديني', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-7', name: 'مستشفى الراعي الصالح', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-8', name: 'الأرض العليا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-9', name: 'شرطة النصر', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-10', name: 'نادي المعلمين', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-11', name: 'مستشفى يحيي راضي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-12', name: 'شارع الكورنيش', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-13', name: 'بوابة المساحة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-14', name: 'كنيسة المزرعة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-15', name: 'طور سينا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-16', name: 'شارع مكي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-17', name: 'مصنع بيبسي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-18', name: 'الجزيرة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-19', name: 'منطقة مخزن الزيت', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-20', name: 'الكوبري العلوي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-21', name: 'إشارة كنتاكي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-22', name: 'الزخرفية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-23', name: 'أبو الريش', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-24', name: 'وجيه أباظة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-25', name: 'مستشفى عسكري', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-26', name: 'الطرق والكباري', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-27', name: 'أرض نصرة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-28', name: 'الفكرية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-29', name: 'القلعة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-30', name: 'العبارة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-31', name: 'المرور', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-32', name: 'مدينة نصر', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-33', name: 'الإسلامية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-34', name: 'مدخل المحافظة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-35', name: 'فاطمة الزهراء', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-36', name: 'مستشفى رواد الوادي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-37', name: 'دهشور', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-38', name: 'سينما النصر الصيفي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-39', name: 'مستشفى العيون', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-40', name: 'أحمد زويل', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-41', name: 'ساحة الحرية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-42', name: 'البحر', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-43', name: 'السد العالي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-44', name: 'جامع الأتوبيس', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-45', name: 'المشتل', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-46', name: 'الهلال القديم', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-47', name: 'برج الجامعة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-48', name: 'مستشفى الصدر', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-49', name: 'ماركت طيبة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-50', name: 'مضرب الرز', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-51', name: 'جامع التقوى', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-52', name: 'شبرا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-53', name: 'الرويني', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-54', name: 'الضغط العالي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-55', name: 'الماترنتيه', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-56', name: 'أبو عبدالله', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-57', name: 'صلاح الدين', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-58', name: 'المديرية الجديدة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-59', name: 'بيانتو', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-60', name: 'ميدان الساعة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-61', name: 'مستشفى المبرة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-62', name: 'مستشفى دار الأطفال', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-63', name: 'مستشفى دار الأمومة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-64', name: 'مستشفى دار الشفا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-65', name: 'مستشفى دار السلام', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-66', name: 'مستشفى كونكورد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-67', name: 'الرحباية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-68', name: 'الموازين', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-69', name: 'شارع جلال', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-70', name: 'شارع السجن', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-71', name: 'المدينة الصناعية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-72', name: 'بيت المحافظ', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-73', name: 'تشاو مول', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-74', name: 'شارع الجديد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-75', name: 'مسجد رومية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-76', name: 'دوران الاستاد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-77', name: 'صبحي البلكي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-78', name: 'تلاجة مرعي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-79', name: 'شارع 16', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-80', name: 'المشير', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-81', name: 'محمود منصور', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-82', name: 'مدرسة الكارما', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-83', name: 'مدرسة الصفوة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-84', name: 'النفق', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-85', name: 'النادي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-86', name: 'النافورة - الصردي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-87', name: 'جامع الصحابة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-88', name: 'إيليت بلازا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-89', name: 'ادمون', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-90', name: 'سوق سوريا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-91', name: 'المقريزي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-92', name: 'دمنهور للسياحة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-93', name: 'أرض الحوافي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-94', name: 'المحطة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-95', name: 'يوليو 23', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-96', name: 'عرابي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-97', name: 'الصاغة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-98', name: 'مخرطة الجندي أبو الريش', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-99', name: 'الصفتي أبو الريش', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-100', name: 'قاعة الماسة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-101', name: 'قاعة مولن روج قبل الابعادية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-102', name: 'تفرعات الروضة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-103', name: 'شجرة الدر', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-104', name: 'قاعة كيان', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-105', name: 'الحبروك قدام كافيه ع الناصية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-106', name: 'الخيري', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-107', name: 'أرض ادمون', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-108', name: 'مستشفى العام', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-109', name: 'مستشفى ليدي كير', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-110', name: 'الراهبات', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-111', name: 'الصدر', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-112', name: 'من المطعم لشارع عبد السلام الشاذلي بالكامل لحد الكوبري', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-113', name: 'من المطعم نغطى منطقة النادي بالكامل', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-114', name: 'منطقة مسجد عيد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-115', name: 'كوبري فلاقه', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-116', name: 'ماركت العمدة بعد كوبري فلافه', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-117', name: 'منطقة بعد كوبري أبو الريش', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-118', name: 'نادي القوات المسلحة أبو الريش', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-119', name: 'الشريعة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-120', name: 'شركة المياه أبو الريش', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-121', name: 'التأمين الصحي أبو الريش', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-122', name: 'جامع عيد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-123', name: 'مساكن الإمام محمد عبده', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-124', name: 'البطاط أبو الريش', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-125', name: 'السوق الجديد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-126', name: 'مساكن المينا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-127', name: 'جزيرة البط', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-128', name: 'الصوامع بعد الشريعة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-129', name: 'بعد الشريعة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-130', name: 'أبراج اسكندرية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-131', name: 'البشيرع الدولي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-132', name: 'كوبري العمدة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-133', name: 'منطقة الموقف', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-134', name: 'عزبة مظهر', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-135', name: 'مزلقان قراقص', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-136', name: 'فراكه عاشور', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-137', name: 'بنزينة اللواء', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-138', name: 'دمتيوه', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-139', name: 'مستشفى العسكري بعد كبري فلاقة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-140', name: 'مساكن القوات المسلحة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-141', name: 'أبو الريش بعد جامع عيد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-142', name: 'مجمع الكليات', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-143', name: 'مدخل الحوش', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-144', name: 'عزبة العمدة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-145', name: 'قاعة القصر الروماني', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-146', name: 'عزبة أبو حامد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-147', name: 'علي باشا بعد كوبري فلافه', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-148', name: 'سيف الدين بعد كوبري فلافه', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-149', name: 'قاعة الماظة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-150', name: 'القصر الروماني', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-151', name: 'محي الدين', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-152', name: 'كوبري الباشا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-153', name: 'قاعة نيفادا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-154', name: 'قاعة لافلي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-155', name: 'قاعة سهر الليالي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-156', name: 'قاعة همسات', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-157', name: 'قاعة ميرامار', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-158', name: 'قاعة ليالينا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-159', name: 'قاعة إيفنت', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-160', name: 'قاعة ريماس', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-161', name: 'قاعة موناكو', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-162', name: 'قاعة رويال', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-163', name: 'محطة كهرباء الزاوية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-164', name: 'منطقة الأبعادية (دار المسنين)', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-165', name: 'مرور قراقص', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-166', name: 'عزبة المسارع', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-167', name: 'ميراج', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-168', name: 'مزلقان دهشور', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-169', name: 'الحبشي مصنع بيبسي', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-170', name: 'العزبة الحمراء', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-171', name: 'شركة كهرباء الزاوية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-172', name: 'قاعة ديفا', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-173', name: 'كوبري الزاوية القديم', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-174', name: 'شركة الكهرباء الزاوية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-175', name: 'غربال', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-176', name: 'الرداينة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-177', name: 'الدرايسة', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-178', name: 'سجن الأبعادية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-179', name: 'موقف الأبعادية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-180', name: 'منطقة الأبعادية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-181', name: 'الأبعادية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-182', name: 'كوبري الأبعادية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-183', name: 'فلاقه البلد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-184', name: 'بنزينة بترومين أول طريق المحمودية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-185', name: 'كوبري الزاوية الجديد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-186', name: 'المعهد الديني غربال', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-187', name: 'الحمامية', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-188', name: 'قراقص البلد', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'zone-189', name: 'الشراقوه', price: 15, prices: { SHOPPING: 15, EMERGENCY: 20, PICK_DROP: 15, GOVERNORATE: 15 } },
  { id: 'gov-abu-homos', name: 'المراكز المجاورة (أبو حمص / كفر الدوار)', price: 60, prices: { SHOPPING: 60, EMERGENCY: 80, PICK_DROP: 60, GOVERNORATE: 60 } },
  { id: 'gov-cairo', name: 'القاهرة', price: 60, prices: { SHOPPING: 60, EMERGENCY: 80, PICK_DROP: 60, GOVERNORATE: 60 } },
  { id: 'gov-giza', name: 'الجيزة', price: 60, prices: { SHOPPING: 60, EMERGENCY: 80, PICK_DROP: 60, GOVERNORATE: 60 } },
  { id: 'gov-alex', name: 'الإسكندرية', price: 50, prices: { SHOPPING: 50, EMERGENCY: 70, PICK_DROP: 50, GOVERNORATE: 50 } },
  { id: 'gov-dakahlia', name: 'الدقهلية', price: 60, prices: { SHOPPING: 60, EMERGENCY: 80, PICK_DROP: 60, GOVERNORATE: 60 } },
  { id: 'gov-redsea', name: 'البحر الأحمر', price: 80, prices: { SHOPPING: 80, EMERGENCY: 100, PICK_DROP: 80, GOVERNORATE: 80 } },
  { id: 'gov-beheira', name: 'البحيرة (باقي المراكز)', price: 40, prices: { SHOPPING: 40, EMERGENCY: 60, PICK_DROP: 40, GOVERNORATE: 40 } },
  { id: 'gov-fayoum', name: 'الفيوم', price: 60, prices: { SHOPPING: 60, EMERGENCY: 80, PICK_DROP: 60, GOVERNORATE: 60 } },
  { id: 'gov-gharbia', name: 'الغربية', price: 50, prices: { SHOPPING: 50, EMERGENCY: 70, PICK_DROP: 50, GOVERNORATE: 50 } },
  { id: 'gov-ismailia', name: 'الإسماعيلية', price: 60, prices: { SHOPPING: 60, EMERGENCY: 80, PICK_DROP: 60, GOVERNORATE: 60 } },
  { id: 'gov-monufia', name: 'المنوفية', price: 55, prices: { SHOPPING: 55, EMERGENCY: 75, PICK_DROP: 55, GOVERNORATE: 55 } },
  { id: 'gov-minya', name: 'المنيا', price: 70, prices: { SHOPPING: 70, EMERGENCY: 90, PICK_DROP: 70, GOVERNORATE: 70 } },
  { id: 'gov-qalyubia', name: 'القليوبية', price: 60, prices: { SHOPPING: 60, EMERGENCY: 80, PICK_DROP: 60, GOVERNORATE: 60 } },
  { id: 'gov-newvalley', name: 'الوادي الجديد', price: 90, prices: { SHOPPING: 90, EMERGENCY: 110, PICK_DROP: 90, GOVERNORATE: 90 } },
  { id: 'gov-suez', name: 'السويس', price: 60, prices: { SHOPPING: 60, EMERGENCY: 80, PICK_DROP: 60, GOVERNORATE: 60 } },
  { id: 'gov-aswan', name: 'أسوان', price: 80, prices: { SHOPPING: 80, EMERGENCY: 100, PICK_DROP: 80, GOVERNORATE: 80 } },
  { id: 'gov-asyut', name: 'أسيوط', price: 70, prices: { SHOPPING: 70, EMERGENCY: 90, PICK_DROP: 70, GOVERNORATE: 70 } },
  { id: 'gov-benisuef', name: 'بني سويف', price: 65, prices: { SHOPPING: 65, EMERGENCY: 85, PICK_DROP: 65, GOVERNORATE: 65 } },
  { id: 'gov-portsaid', name: 'بورسعيد', price: 60, prices: { SHOPPING: 60, EMERGENCY: 80, PICK_DROP: 60, GOVERNORATE: 60 } },
  { id: 'gov-damietta', name: 'دمياط', price: 60, prices: { SHOPPING: 60, EMERGENCY: 80, PICK_DROP: 60, GOVERNORATE: 60 } },
  { id: 'gov-sharqia', name: 'الشرقية', price: 55, prices: { SHOPPING: 55, EMERGENCY: 75, PICK_DROP: 55, GOVERNORATE: 55 } },
  { id: 'gov-southsinai', name: 'جنوب سيناء', price: 90, prices: { SHOPPING: 90, EMERGENCY: 110, PICK_DROP: 90, GOVERNORATE: 90 } },
  { id: 'gov-kafralsheikh', name: 'كفر الشيخ', price: 45, prices: { SHOPPING: 45, EMERGENCY: 65, PICK_DROP: 45, GOVERNORATE: 45 } },
  { id: 'gov-matrouh', name: 'مطروح', price: 70, prices: { SHOPPING: 70, EMERGENCY: 90, PICK_DROP: 70, GOVERNORATE: 70 } },
  { id: 'gov-qena', name: 'قنا', price: 75, prices: { SHOPPING: 75, EMERGENCY: 95, PICK_DROP: 75, GOVERNORATE: 75 } },
  { id: 'gov-northsinai', name: 'شمال سيناء', price: 90, prices: { SHOPPING: 90, EMERGENCY: 110, PICK_DROP: 90, GOVERNORATE: 90 } },
  { id: 'gov-sohag', name: 'سوهاج', price: 70, prices: { SHOPPING: 70, EMERGENCY: 90, PICK_DROP: 70, GOVERNORATE: 70 } },
  { id: 'gov-luxor', name: 'الأقصر', price: 75, prices: { SHOPPING: 75, EMERGENCY: 95, PICK_DROP: 75, GOVERNORATE: 75 } }
];

// Workflow: Defines the Next Status, Label, and if Photo is required
export const WORKFLOW_CONFIG = {
  [OrderType.SHOPPING]: {
    [OrderStatus.ACCEPTED]: { next: OrderStatus.PICKED_UP, requireProof: false, label: "تم شراء الطلب" },
    [OrderStatus.PICKED_UP]: { next: OrderStatus.ON_THE_WAY, requireProof: false, label: "بدء التوصيل" },
    [OrderStatus.ON_THE_WAY]: { next: OrderStatus.DELIVERED, requireProof: true, label: "تم التوصيل" },
  },
  [OrderType.EMERGENCY]: {
    [OrderStatus.ACCEPTED]: { next: OrderStatus.ON_THE_WAY, requireProof: false, label: "بدء مشوار رايح جاي" },
    [OrderStatus.ON_THE_WAY]: { next: OrderStatus.DELIVERED, requireProof: true, label: "تم إنهاء المشوار بنجاح" },
  },
  [OrderType.PICK_DROP]: {
    [OrderStatus.ACCEPTED]: { next: OrderStatus.PICKED_UP, requireProof: true, label: "تم استلام الطلب من الراسل" },
    [OrderStatus.PICKED_UP]: { next: OrderStatus.ON_THE_WAY, requireProof: false, label: "في الطريق للمستلم" },
    [OrderStatus.ON_THE_WAY]: { next: OrderStatus.DELIVERED, requireProof: true, label: "تم تسليم الطلب" },
  },
  [OrderType.GOVERNORATE]: {
    [OrderStatus.ACCEPTED]: { next: OrderStatus.PICKED_UP, requireProof: true, label: "تم استلام الشحنة" },
    [OrderStatus.PICKED_UP]: { next: OrderStatus.ON_THE_WAY, requireProof: false, label: "جاري الشحن للمحافظة" },
    [OrderStatus.ON_THE_WAY]: { next: OrderStatus.DELIVERED, requireProof: true, label: "تم تسليم الشحنة" },
  },
};

export const ORDER_TYPE_LABELS: Record<OrderType, string> = {
  [OrderType.SHOPPING]: "مشتريات",
  [OrderType.EMERGENCY]: "رايح جاي",
  [OrderType.PICK_DROP]: "توصيل/استلام طرد",
  [OrderType.GOVERNORATE]: "شحن محافظات"
};

// CLEARED FOR PRODUCTION - USERS LOADED FROM DB
export const MOCK_USERS: User[] = [];

// CLEARED FOR PRODUCTION - ORDERS LOADED FROM DB
export const INITIAL_ORDERS: Order[] = [];
