import React, { createContext, useContext, useState, useEffect } from 'react';
export type Language = 'ar' | 'en';
export type TranslationKey = keyof typeof translations['ar'];
export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey | string, fallback?: string) => string;
  dir: 'rtl' | 'ltr';
  isAr: boolean;
  isEn: boolean;
  alignLeft: string;
  alignRight: string;
}
const translations = {
  ar: {
    // Nav
    home: "الرئيسية",
    orders: "طلباتي",
    chats: "الرسائل",
    profile: "حسابي",
    settings: "الإعدادات",
    privacy: "سياسة الخصوصية",
    addresses: "العناوين المسجلة",
    logOut: "تسجيل الخروج",
    // Login screen
    welcomeTitle: "وحشتنا يا بطل! 👋",
    welcomeSubtitle: "سجل دخولك عشان نبدأ يومنا",
    joinTitle: "انضم لـ مشاوير دمنهور ✨",
    joinSubtitle: "عشان أسرع دليفري وتتبع يوصلك لحد باب البيت",
    phoneLabel: "رقم الموبايل",
    passwordLabel: "كلمة السر",
    confirmPasswordLabel: "تأكيد السر",
    fullNameLabel: "الاسم بالكامل",
    addressLabel: "العنوان بالتفصيل",
    rememberMe: "تذكرني",
    forgotPassword: "نسيت الباسورد؟",
    loginBtn: "يلا بينا (دخول)",
    registerBtn: "إنشاء حساب جديد",
    noAccount: "معندكش حساب؟",
    registerHereNow: "سجل هنا دلوقتي",
    demoQuickLogin: "نسخة ديمو: دخول سريع",
    admin: "أدمن 👑",
    captain: "كابتن 🛵",
    customer: "عميل 👤",
    loading: "جاري التحميل...",
    // Settings Screen
    settingsTitle: "الإعدادات",
    notifications: "الإشعارات",
    darkMode: "الوضع الليلي",
    sounds: "الأصوات",
    language: "اللغة (Language)",
    reportIssue: "الإبلاغ عن مشكلة تقنية",
    changePassword: "تغيير كلمة المرور",
    arabic: "العربية",
    english: "English",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    saveChanges: "حفظ التغييرات",
    sendReport: "إرسال البلاغ",
    describeIssue: "صف المشكلة التي تواجهها بالتفصيل",
    writeHere: "اكتب هنا...",
    logoutConfirmTitle: "تسجيل الخروج؟",
    logoutConfirmDesc: "هل أنت متأكد أنك تريد الخروج من الحساب؟",
    cancel: "إلغاء",
    exit: "خروج",
    // Double order / preferences
    allowDoubleOrder: "السماح بتوصيل مشترك لطيار آخر؟",
    allowDoubleOrderDescAccept: "✅ أنت تسمح للمندوب بحمل طلب آخر معك إذا كان في نفس طريقك لتوفير الوقت والجهد.",
    allowDoubleOrderDescReject: "🚫 طلب منفرد وسريع: يمنع المندوب تماماً من حمل أي طلب آخر حتى يسلم طلبك بالسلامة.",
    allowDoubleOrderMerchant: "هل تسمح للطيار بحمل طلب إضافي مع طلبك؟",
    allowDoubleOrderMerchantAccept: "✅ سماح: يمكن للمندوب دمج الطلب مع طلب آخر في طريقه.",
    allowDoubleOrderMerchantReject: "🚫 منع (شحن منفرد سريع): يجب على المندوب العمل على هذا الطلب حصرياً حتى تسليمه.",
    deliveryPreference: "تفضيل الشحن",
    allowedDoubleOrderBadge: "🔄 مسموح بالدمج",
    soloOrderBadge: "🔒 شحن منفرد فقط",
    doubleOrderAllowedMsg: "🔄 مسموح بتوصيل طلب مشترك آخر لتوفير الوقت",
    doubleOrderSoloMsg: "🔒 شحن منفرد وسريع: يمنع تجميع طلبات أخرى معه",
    // General Words
    currency: "جنيه",
    sendToCaptain: "إرسال للكابتن",
    customerName: "اسم العميل",
    deliveryCode: "كود الاستلام",
    priceText: "السعر",
    itemCost: "ثمن المشتريات",
    recipientPhone: "رقم المستلم",
    notes: "ملاحظات",
    zone: "المنطقة",
    addAddress: "إضافة عنوان جديد",
    voiceNotes: "الرسائل الصوتية",
    successCode: "✅ تم تأكيد الاستلام بنجاح!",
    errorCode: "❌ كود خاطئ أو طلب غير صالح.",
    connectionError: "مشكلة في الاتصال بقاعدة البيانات.. يرجى الانتظار",
    technicalSupport: "الدعم الفني",
    support24: "نحن هنا لمساعدتك 24/7",
    selectChannel: "اختر وسيلة التواصل",
    contactWA: "تواصل عبر واتساب",
    contactCall: "اتصال هاتفي",
    statusText: "الحالة",
    newOrderAlert: "طلب جديد متاح! 📦",
    newOrderAlertBody: "يوجد طلب جديد في {address}. اضغط للقبول.",
    offlineAlert: "لا يوجد اتصال بالإنترنت! ⚠️",
    // Dashboard Details
    goodMorning: "صباح الفل ✨",
    dashboard: "لوحة التحكم",
    updatePasswordSuccess: "تم التغيير بنجاح",
    reportSentSuccess: "تم استلام بلاغك وسيقوم الدعم الفني بمراجعته.",
    currentBalance: "الرصيد الحالي",
    history: "السجل التاريخي",
    activeOrders: "الطلبات النشطة",
    availableOrders: "الطلبات المتاحة",
    addOrderBtn: "إنشاء طلب جديد",
    myOrders: "طلباتي",
    deliveryCost: "تكلفة التوصيل",
    resetGuide: "إعادة تعيين دليل الاستخدام",
    geoError: "خطأ في النطاق الجغرافي",
    connectionIssue: "مشكلة في الاتصال",
    connectionErrorFull: "فشل الاتصال بقاعدة البيانات. تأكد من أنك متصل بالإنترنت.",
    refreshPage: "تحديث الصفحة 🔄",
    contactSupport: "تواصل مع الدعم الفني 🎧",
    appName: "عالطاير",
    youAreOnline: "أنت متاح دلوقتى",
    youAreOffline: "أنت غير متاح",
    ordersWillReachYou: "الطلبات هتوصلك فوراً",
    clickToStart: "اضغط للبدء واستقبال طلبات",
    overallPerformance: "تقييم الأداء العام",
    details: "التفاصيل",
    totalOrders: "طلب (الكلي)",
    newOrdersTab: "جديدة",
    activeOrdersTab: "جارية",
    noOrdersNow: "لا توجد طلبات حالياً",
    youAreOfflineStatus: "أنت غير متاح حالياً",
    changeStatusToReceive: "قم بتغيير حالتك إلى متاح لاستقبال طلبات جديدة",
    acceptOrderCode: "إدخال كود الاستلام",
    askCustomerForCode: "اطلب الكود من العميل للتأكيد",
    confirmDelivery: "تأكيد الاستلام",
    codeMissingError: "برجاء إدخال الكود أولاً",
    distanceCalcError: "تعذر حساب المسافة",
    driverInfoMissing: "بيانات المندوب غير مكتملة",
    deliveryCompleted: "تم توصيل الطلب بنجاح!",
    detailsMissing: "يجب ملء التفاصيل",
    recipientMissing: "يجب إدخال اسم المستلم",
    finishDelivery: "إنهاء التوصيل",
    ar_1: "٠١٢٣٤٥٦٧٨٩",
    ar_2: "هادية ❄️",
    ar_3: "ولعة 🔥",
    ar_4: "متوسطة ⚡",
    ar_5: "مكتمل",
    ar_6: "جاري",
    ar_7: "ملغي",
    ar_8: "اليوم",
    ar_9: "أمس",
    ar_10: "الاسم مطلوب",
    ar_11: "حذف المنطقة",
    ar_12: "هل أنت متأكد من حذف هذه المنطقة؟ قد يؤثر ذلك على الطلبات القديمة.",
    ar_13: "نعم، احذف",
    ar_14: "تراجع",
    ar_15: "من فضلك املأ جميع البيانات",
    ar_16: "أدمن",
    ar_17: "موظف",
    ar_18: "كابتن",
    ar_19: "فشل الإضافة",
    ar_20: "الموافقة على إلغاء الطلب",
    ar_21: "هل أنت متأكد من رغبتك في الموافقة على إلغاء هذا الطلب نهائياً وإرجاعه؟",
    ar_22: "نعم، وافق على الإلغاء",
    ar_23: "رفض طلب الإلغاء",
    ar_24: "هل تريد رفض طلب الإلغاء وإبقاء المشوار فعالاً مع المندوب؟",
    ar_25: "نعم، ارفض طلب الإلغاء",
    ar_26: "تم تحديث بيانات المستخدم بنجاح",
    ar_27: "فشل التحديث",
    ar_28: "إلغاء حظر المستخدم",
    ar_29: "حظر المستخدم",
    ar_30: "فك الحظر",
    ar_31: "نعم، احظر المستخدم",
    ar_32: "غير معين",
    ar_33: "غير معروف",
    ar_34: "الرئيسية",
    ar_35: "الخريطة",
    ar_36: "الطلبات",
    ar_37: "الكباتن",
    ar_38: "العملاء",
    ar_39: "التحليلات",
    ar_40: "الماليات",
    ar_41: "خريطة الحرارة",
    ar_42: "إدارة",
    ar_43: "الإشعارات",
    ar_44: "الإعدادات",
    ar_45: "الرجوع للرئيسية",
    ar_46: "نظرة سريعة 📊",
    ar_47: "خريطة التتبع 🗺️",
    ar_48: "كل الطلبات 📦",
    ar_49: "أبطالنا 🏎️",
    ar_50: "إدارة الأعضاء 👥",
    ar_51: "عملاؤنا 👨‍👩‍👧‍👦",
    ar_52: "التقارير المالية 💰",
    ar_53: "تحليل الأداء 📈",
    ar_54: "إرسال إشعار 🔔",
    ar_55: "ضبط النظام ⚙️",
    ar_56: "سحب الموقع الآن",
    ar_57: "إيرادات اليوم",
    ar_58: "محدث لحظياً",
    ar_59: "إيرادات الشهر",
    ar_60: "من بداية الشهر الحالي",
    ar_61: "الإجمالي الكلي",
    ar_62: "منذ تاريخ التأسيس",
    ar_63: "تفاصيل دخل الحسابات (المناديب)",
    ar_64: "المندوب",
    ar_65: "الشهر",
    ar_66: "الإجمالي",
    ar_67: "لا يوجد مناديب مسجلين حالياً",
    ar_68: "طلبات إلغاء ضرورية! (",
    ar_69: "طلب #",
    ar_70: "تحتاج موافقة",
    ar_71: "السبب:",
    ar_72: "موافقة",
    ar_73: "رفض",
    ar_74: "عرض تفاصيل الطلب بالكامل",
    ar_75: "دخل النهاردة",
    ar_76: "إجمالي الطلبات",
    ar_77: "طيار نشط",
    ar_78: "عميل مسجل",
    ar_79: "أدوات النظام السريعة",
    ar_80: "لوحة التحكم",
    ar_81: "الخريطة المباشرة",
    ar_82: "تتبع الكباتن والطلبات",
    ar_83: "إنشاء أوردر",
    ar_84: "إنشاء أوردر لعميل",
    ar_85: "إدارة الكباتن",
    ar_86: "تتبع الكباتن وتقييماتهم",
    ar_87: "تحليل الأداء",
    ar_88: "أداء الكباتن والطلبات",
    ar_89: "أماكن تركز الطلبات",
    ar_90: "قائمة العملاء",
    ar_91: "بيانات وعناوين العملاء",
    ar_92: "التقارير المالية",
    ar_93: "إيرادات اليوم والشهر",
    ar_94: "إدارة الأعضاء",
    ar_95: "تعديل وحظر الحسابات",
    ar_96: "إرسال إشعار جماعي",
    ar_97: "تنبيهات جماعية للهواتف",
    ar_98: "ضبط النظام",
    ar_99: "إضافة مناديب ومحافظات وتسعير",
    ar_100: "ابحث بالاسم أو الرقم...",
    ar_101: "حفظ ✅",
    ar_102: "إلغاء",
    ar_103: "إضافة كابتن",
    ar_104: "إضافة أدمن",
    ar_105: "إضافة موظف",
    ar_106: "أسعار شحن المناطق",
    ar_107: "أسعار شحن المحافظات",
    ar_108: "تسجيل كابتن جديد",
    ar_109: "تسجيل مسؤول جديد",
    ar_110: "تسجيل موظف جديد",
    ar_111: "الاسم",
    ar_112: "الاسم الثلاثي",
    ar_113: "رقم الموبايل",
    ar_114: "كلمة المرور",
    ar_115: "جاري الإضافة...",
    ar_116: "الكابتن",
    ar_117: "الأدمن",
    ar_118: "الموظف",
    ar_119: "اسم المنطقة الجديدة",
    ar_120: "مثال: دمنهور - حي الزهور",
    ar_121: "مشتريات وتوصيل",
    ar_122: "مشوار رايح جاي",
    ar_123: "توصيل",
    ar_124: "تمت إضافة المنطقة بنجاح",
    ar_125: "إضافة المنطقة بأسعارها",
    ar_126: "تم تعديل المنطقة",
    ar_127: "حفظ",
    ar_128: "مشتريات:",
    ar_129: "ج.م",
    ar_130: "رايح جاي:",
    ar_131: "توصيل:",
    ar_132: "اسم المحافظة الجديدة",
    ar_133: "مثال: أسوان",
    ar_134: "سعر الشحن",
    ar_135: "اسم المحافظة مطلوب",
    ar_136: "تمت إضافة المحافظة بنجاح",
    ar_137: "إضافة المحافظة بسعر الشحن",
    ar_138: "تم تعديل سعر المحافظة",
    ar_139: "سعر الشحن:",
    ar_140: "ابحث برقم الطلب، العميل، المتجر، أو العناصر...",
    ar_141: "🟢 متاح للعمل",
    ar_142: "🔴 غير متاح",
    ar_143: "تقييم)",
    ar_144: "دقيقة",
    ar_145: "طلب ناجح",
    ar_146: "بيوصل طلب دلوقتى",
    ar_147: "مفيش طلبات معاه",
    ar_148: "سجل طلبات الكابتن",
    ar_149: "المركز",
    ar_150: "القوة الإنتاجية",
    ar_151: "الطلبات المكتملة",
    ar_152: "إجمالي الإيرادات",
    ar_153: "متوسط الوقت",
    ar_154: "د",
    ar_155: "أداء المنطقة:",
    ar_156: "ممتاز 🔥",
    ar_157: "خريطة كثافة الطلبات (Heatmap)",
    ar_158: "توضح مناطق تركز الطلبات بناءً على النطاق الزمني المحدد للمساعدة في إعادة توزيع الطيارين.",
    ar_159: "القائمة",
    ar_160: "ضغط عالي",
    ar_161: "متوسط",
    ar_162: "لا توجد طلبات في هذا النطاق الزمني",
    ar_163: "غير محدد",
    ar_164: "لا يوجد عملاء مسجلين",
    ar_165: "العناوين",
    ar_166: "إجمالي التحصيل",
    ar_167: "لا يوجد سجل طلبات مكتملة",
    ar_168: "تم",
    ar_169: "دع الكابتن يمسح الكود أو أرسله له",
    ar_170: "إرسال للكابتن عبر واتساب",
    ar_171: "هل أنت متأكد من رغبتك في إلغاء هذا الطلب نهائياً؟",
    ar_172: "الميكروفون غير مدعوم في هذا المتصفح.",
    ar_173: "برجاء السماح بالوصول للمايكروفون",
    ar_174: "حجم الصورة كبير جداً (الأقصى 5 ميجا)",
    ar_175: "برجاء إدخال تفاصيل الطلب",
    ar_176: "الراسل",
    ar_177: "المستلم",
    ar_178: "اختر عنوان التوصيل",
    ar_179: "اسم المكان مطلوب",
    ar_180: "اختر عنوانك الأساسي (الرجوع إليه)",
    ar_181: "عنوان الوجهة مطلوب",
    ar_182: "عنوان استلام الطرد مطلوب",
    ar_183: "عنوان المستلم مطلوب",
    ar_184: "منطقة المستلم مطلوبة",
    ar_185: "رقم المستلم مطلوب",
    ar_186: "توصيل طرد",
    ar_187: "استلام طرد",
    ar_188: "شحن محافظات",
    ar_189: "عنوان المستلم (طرد)",
    ar_190: "املأ البيانات",
    ar_191: "جهازك لا يدعم تحديد الموقع الجغرافي",
    ar_192: "موقعي الحالي",
    ar_193: "فشل تحديد الموقع. تأكد من تشغيل GPS والسماح للمتصفح بالوصول لموقعك.",
    ar_194: "عناويني",
    ar_195: "📍 موقع GPS",
    ar_196: "إضافة عنوان جديد",
    ar_197: "استخدام موقعي الحالي (GPS)",
    ar_198: "سيتم كتابة العنوان تلقائياً",
    ar_199: "تم تحديد الإحداثيات والعنوان بنجاح",
    ar_200: "اسم العنوان",
    ar_201: "مثال: البيت، المكتب",
    ar_202: "المنطقة التابع لها",
    ar_203: "تفاصيل العنوان (الشارع، العمارة...)",
    ar_204: "اكتب العنوان بالتفصيل هنا...",
    ar_205: "تعديل الموقع على الخريطة يدوياً:",
    ar_206: "حفظ هذا العنوان",
    ar_207: "اسم المطعم أو المحل (اختياري)",
    ar_208: "مثال: كنتاكي، صيدلية العزبي",
    ar_209: "وصف المشتريات بدقة",
    ar_210: "اكتب طلبك بالتفصيل هنا...",
    ar_211: "رايح جاي: الكابتن هياخد منك حاجة يوصلها لمكان ويرجعلك بحاجة تانية من هناك.",
    ar_212: "الوجهة (المكان اللي الكابتن هيروحله ويرجع منه)",
    ar_213: "مثال: شارع المحطة بجوار البوسطة...",
    ar_214: "تفاصيل المشوار",
    ar_215: "مثال: هياخد أوردر يوديه ويرجع بفلوس...",
    ar_216: "اختر نوع خدمة الطرد:",
    ar_217: "يرجى تحديد ما إذا كنت تريد إرسال أو استقبال طرد",
    ar_218: "توصيل طرد (هبعت طرد لشخص آخر) 📤",
    ar_219: "عايز الكابتن ييجي يستلم مني طرد ويوصله لعنوان شخص آخر.",
    ar_220: "استلام طرد (هجيب طرد من شخص آخر) 📥",
    ar_221: "عايز الكابتن يروح يجيب طرد من مكان أو شخص تاني ويسلمهولي في مكاني.",
    ar_222: "ارسال من دمنهور الى جميع المحافظات",
    ar_223: "يرجى اختيار المحافظة المقصودة أدناه، وسيتحدّد سعر الشحن الخاص بها تلقائياً.",
    ar_224: "توصيل طرد (هبعت)",
    ar_225: "استلام طرد (هجيب)",
    ar_226: "وصف الشحنة/الطرد",
    ar_227: "مثال: شنطة ملابس، أوراق مهمة...",
    ar_228: "منين (عنوان الراسل - أنا):",
    ar_229: "منين (المكان اللي هنجيب منه الطرد):",
    ar_230: "منين (الراسل):",
    ar_231: "عنوان الاستلام",
    ar_232: "الشارع، رقم العمارة، المنطقة...",
    ar_233: "رقم هاتف الراسل",
    ar_234: "على فين (المكان اللي هنودي ليه الطرد):",
    ar_235: "على فين (عنوان المستلم - أنا):",
    ar_236: "على فين (المستلم):",
    ar_237: "رقم هاتف المستلم",
    ar_238: "محافظة المستلم",
    ar_239: "منطقة المستلم",
    ar_240: "(للسعر)",
    ar_241: "اختر المنطقة",
    ar_242: "عنوان المستلم بالتفصيل",
    ar_243: "الشارع، رقم العمارة، الطابق...",
    ar_244: "أضف تفاصيل إضافية (اختياري)",
    ar_245: "صورة الطلب",
    ar_246: "تسجيل يدوي: انقر مجدداً للحفظ 💾",
    ar_247: "أو اسحب إصبعك للإلغاء",
    ar_248: "سجل طلبك فويس 🎤",
    ar_249: "اضغط مطولاً أو نقرة واحدة للبدء",
    ar_250: "رسالة صوتية للطلب",
    ar_251: "على فين (عنوان التوصيل إليك)",
    ar_252: "جديد",
    ar_253: "برجاء إضافة عنوان أولاً",
    ar_254: "تحصيل / دفع كاش",
    ar_255: "فعل هذا الخيار إذا كان الكابتن سيقوم بدفع مبلغ للمحل أو إذا كان سيقوم بتحصيل مبلغ من المستلم.",
    ar_256: "المبلغ (بدون التوصيل)",
    ar_257: "مين اللي هيدفع مصاريف التوصيل؟",
    ar_258: "سعر التوصيل:",
    ar_259: "مبلغ التحصيل:",
    ar_260: "الإجمالي:",
    ar_261: "(سيتم دفع التوصيل بواسطة",
    ar_262: "أكّد الطلب يا بطل 🚀",
    ar_263: "إغلاق الدليل",
    ar_264: "💡 دليل الاستخدام السريع",
    ar_265: "ازاي تستخدم تطبيق الطيار؟ 🛵",
    ar_266: "افهم نظام عالطاير في 3 خطوات بسيطة وممتازة",
    ar_267: "١",
    ar_268: "اطلب مشوارك 📝",
    ar_269: "اختر الخدمة (طعام🛒، طرد📦، رايح جاي🔄) واكتب طلبك. يمكنك تسجيل فويس نوت أو رفع صورة لتسهيل الشرح للطيار!",
    ar_270: "٢",
    ar_271: "اختر السعر والطيار 🤝",
    ar_272: "المناديب القريبين سيتنافسون على طلبك ويقترحون أسعار توصيل مخصصة. قارن بين أسعارهم وتقييماتهم، واقبل العرض الأفضل لك!",
    ar_273: "٣",
    ar_274: "تتبع لايف ودردش 🗺️",
    ar_275: "بعد القبول، دردش مع الكابتن بشات ميز ممتاز وتتبع خط سير المندوب لايف على الخريطة وسلّم بأمان عبر رمز QR.",
    ar_276: "جاهز للبدء؟ اطلب أول أوردر ليك وجرب السرعة 🚀",
    ar_277: "فهمت، اخفِ الدليل 🤝",
    ar_278: "عايز توصّل إيه؟ ✨",
    ar_279: "اختار نوع الطلب",
    ar_280: "مشتريات ودليفري",
    ar_281: "شائع",
    ar_282: "وجبات، بقالة، صيدلية",
    ar_283: "من مكان لمكان",
    ar_284: "مشوار رايح جاي",
    ar_285: "توصيل والرجوع بشيء",
    ar_286: "شحن محافظات مصر 🌎",
    ar_287: "من دمنهور لجميع المحافظات",
    ar_288: "طلباتك",
    ar_289: "تابع حالة طلباتك أولاً بأول",
    ar_290: "طلبات حالية (",
    ar_291: "السابق (",
    ar_292: "مفيش طلبات",
    ar_293: "اطلب أوردر دلوقتي",
    ar_294: "الحساب",
    ar_295: "الشات",
    ar_296: "الكود",
    ar_297: "تنبيه طارئ: تم إبلاغ الشركة!",
    ar_298: "تحذير: أنت غير نشط منذ 10 دقائق",
    ar_299: "يرجى التحرك الآن فوراً لتجنب إرسال بلاغ خمول للإدارة.",
    ar_300: "خطأ في النطاق الجغرافي",
    ar_301: "لإنهاء الطلب، يرجى إدخال الكود المستلم من العميل.",
    ar_302: "حدث خطأ أثناء تحديث حالة الطلب",
    ar_303: "الكود قصير جداً (لازم 6 أرقام)",
    ar_304: "الكود ده بتاع أوردر تاني خالص! راجع الكود.",
    ar_305: "الكود ده مش صح أو الأوردر اتسلم فعلاً",
    ar_306: "رقم الهاتف غير متوفر",
    ar_307: "تنبيه طارئ: تم إبلاغ الشركة بوقوفك!",
    ar_308: "أنت واقف بقالك فترة طويلة (",
    ar_309: "دقيقة). تم إرسال تنبيه خمول تلقائياً للشركة وللإدارة. يرجى التحرك فوراً لاستقبال أوردرات جديدة.",
    ar_310: "تحذير خمول: يرجى التحرك الآن!",
    ar_311: "أنت واقف بقالك",
    ar_312: "دقائق. إذا استمر وقوفك لمدة 15 دقيقة، سيتم إرسال بلاغ خمول طارئ للشركة تلقائياً!",
    ar_313: "تقييمات الأداء",
    ar_314: "التقييم العام:",
    ar_315: "لا توجد تقييمات مسجلة بعد",
    ar_316: "غير متوفر",
    ar_317: "تحقق وتسليم",
    ar_318: "تأكيد تفاصيل التسليم",
    ar_319: "يرجى التحقق من الطرد والمستلم قبل إنهاء الطلب",
    ar_320: "تفاصيل الطرد والشحنة",
    ar_321: "محتويات الطلب:",
    ar_322: "الحساب الكلي:",
    ar_323: "قيمة التحصيل / الطرد:",
    ar_324: "من سيدفع التوصيل؟",
    ar_325: "بيانات المستلم والتوصيل",
    ar_326: "رقم المستلم:",
    ar_327: "العنوان:",
    ar_328: "لقد قمت بمراجعة محتويات الطرد ومطابقة القيمة المالية المطلوبة للتحصيل.",
    ar_329: "لقد تحققت من مستلم الشحنة الحالي وهويته بمطابقة بيانات المستلم والعميل.",
    ar_330: "✅ كود صحيح! تم تسليم الطلب بنجاح ومراجعة التفاصيل.",
    ar_331: "إكمال عملية التسليم وتأكيدها",
    ar_332: "تعديل الكود / رجوع",
    ar_333: "أكملت",
    ar_334: "لقد وصلت للحد الأقصى (4 طلبات). أكمل ما معك لاستقبال المزيد.",
    ar_335: "جديدة (",
    ar_336: "جارية (",
    ar_337: "تحديث",
    ar_338: "بدء العمل الآن",
    ar_339: "العميل يتابعك الآن",
    ar_340: "تتبع مباشر مفعل",
    ar_341: "تنبيه هام!",
    ar_342: "الاوردر في حالة الغاء برجاء التواصل مع الادارة لمعرفة تكملة الاوردر ام لا",
    ar_343: "يوجد صورة",
    ar_344: "يوجد فويس نوت",
    ar_345: "إدخال كود الاستلام",
    ar_346: "مكتملة",
    ar_347: "المحادثة (شات)",
    ar_348: "واتساب",
    ar_349: "اتصال",
    ar_350: "تفاصيل",
    ar_351: "اكتمل (4)",
    ctx_500: "تم حظر حسابك. يرجى مراجعة الإدارة.",
    ctx_501: "فشل الاتصال بقاعدة البيانات.",
    ctx_502: "تحذير: توقف طويل ⚠️",
    ctx_503: "تنبيه: تم إرسال بلاغ 🚨",
    ctx_504: "تنبيه خمول طارئ 🚨",
    ctx_505: "فقدان إشارة GPS 📡",
    ctx_506: "تم الموافقة على طلبك! ✅",
    ctx_507: "تم إلغاء الطلب 🚫",
    ctx_508: "طلب جديد متاح! 📦",
    ctx_509: "🚨 طلب إلغاء عاجل!",
    ctx_510: "تم حظر حسابك من قبل الإدارة.",
    ctx_511: "إشعار جديد",
    ctx_512: "جاري الاتصال بقاعدة البيانات.. يرجى الانتظار",
    ctx_513: "الرقم لازم يبقا 11 رقم",
    ctx_514: "الرقم مش متسجل أو كلمة المرور خطأ (أو الحساب محظور)",
    ctx_515: "فشل الاتصال بالخادم. حاول مرة أخرى.",
    ctx_516: "فشل تسجيل الدخول بجوجل",
    ctx_517: "فشل الاتصال بالخادم",
    ctx_518: "فشل إكمال التسجيل",
    ctx_519: "كلمة المرور قصيرة جداً",
    ctx_520: "حدث خطأ",
    ctx_521: "فشل إنشاء المستخدم",
    ctx_522: "فشل في إنشاء الطلب.",
    ctx_523: "خطأ في الاتصال بالخادم",
    ctx_524: "⚠️ لا يمكنك حمل أكثر من 4 طلبات في نفس الوقت.",
    ctx_525: "عذراً، قام كابتن آخر بقبول الطلب قبلك بثواني.",
    ctx_526: "خطأ في الاتصال",
    ctx_527: "تم تسليم طلبك 🎉",
    ctx_528: "لا يمكنك تأكيد تسليم أوردر غير مسند إليك",
    ctx_529: "❌ تم رفض طلب الإلغاء من قبل الإدارة ومتابعة التوصيل.",
    ctx_530: "الكابتن",
    ctx_531: "العميل",
    ctx_532: "تم إلغاء الطلب من قبل الإدارة.",
    ctx_533: "⚠️ لا يمكن تحديد موقعك. تأكد من تفعيل الـ GPS لتأكيد التوصيل.",
    ctx_534: "غير مسجل دخول",
    ctx_535: "كلمة المرور الجديدة قصيرة جداً",
    ctx_536: "تم تغيير كلمة المرور بنجاح",
    ctx_537: "فشل تحديث قاعدة البيانات",
    ctx_538: "المبلغ غير صالح",
    ctx_539: "فشل شحن الرصيد",
    ctx_540: "الرصيد غير كافٍ",
    ctx_541: "فشل سحب الرصيد - تأكد من الرصيد المتاح",
    ctx_542: "فشل سحب الرصيد",
    ctx_543: "🎤 رسالة صوتية",
    ctx_544: "📷 صورة",
    ar_all_1000: "المحفظة",
    ar_all_1001: "الرصيد الحالي",
    ar_all_1002: "شحن رصيد",
    ar_all_1003: "سحب رصيد",
    ar_all_1004: "المبلغ",
    ar_all_1005: "جاري التنفيذ...",
    ar_all_1006: "تأكيد",
    ar_all_1007: "آخر العمليات",
    ar_all_1008: "لا توجد عمليات حديثة",
    ar_all_1009: "وصول المندوب خلال",
    ar_all_1010: "تتبع مباشر",
    ar_all_1011: "المندوب",
    ar_all_1012: "في الطريق إليك",
    ar_all_1013: "طلب جديد",
    ar_all_1014: "اسم العميل",
    ar_all_1015: "مثال: أحمد محمد",
    ar_all_1016: "تفاصيل الطلب",
    ar_all_1017: "قائمة الأصناف...",
    ar_all_1018: "عنوان التوصيل",
    ar_all_1019: "الشارع، رقم العمارة، الشقة",
    ar_all_1020: "المنطقة",
    ar_all_1021: "إرسال للكابتن",
    ar_all_1022: "بحث في طلبات المتجر...",
    ar_all_1023: "طلبات قيد التوصيل",
    ar_all_1024: "كل الطلبات مكتملة",
    ar_all_1025: "جاري البحث...",
    ar_all_1026: "الكابتن",
    ar_all_1027: "الكل",
    ar_all_1028: "مكتمل",
    ar_all_1029: "إيراد",
    ar_all_1030: "في الانتظار",
    ar_all_1031: "تم القبول",
    ar_all_1032: "تم دفع الفاتورة",
    ar_all_1033: "قيد التحضير",
    ar_all_1034: "تم الاستلام",
    ar_all_1035: "في الطريق",
    ar_all_1036: "تم التوصيل",
    ar_all_1037: "مرتجع",
    ar_all_1038: "ملغي",
    ar_all_1039: "تم إعادة التعيين بنجاح. سيظهر الدليل عند فتح الرئيسية.",
    ar_all_1040: "نجاح",
    ar_all_1041: "تعذر الوصول للكاميرا. تأكد من السماح بالصلاحيات أو استخدم رفع الصورة.",
    ar_all_1042: "لم يتم العثور على كود QR صالح في الصورة. حاول مرة أخرى بصورة أوضح.",
    ar_all_1043: "مسح كود الاستلام",
    ar_all_1044: "الكاميرا غير متاحة",
    ar_all_1045: "رفع صورة بدلاً من ذلك",
    ar_all_1046: "جاري تحليل الصورة...",
    ar_all_1047: "وجه الكاميرا نحو رمز QR الخاص بالعميل",
    ar_all_1048: "رفع صورة",
    ar_all_1049: "المسح تلقائي بمجرد رؤية الكود",
    ar_all_1050: "اختر وسيلة التواصل",
    ar_all_1051: "تواصل عبر واتساب",
    ar_all_1052: "اتصال هاتفي",
    ar_all_1053: "الاسم مطلوب",
    ar_all_1054: "تم تحديث البيانات بنجاح",
    ar_all_1055: "فشل التحديث. حاول مرة أخرى.",
    ar_all_1056: "الاسم",
    ar_all_1057: "رقم الهاتف",
    ar_all_1058: "لتغيير الرقم يرجى التواصل مع الدعم",
    ar_all_1059: "حفظ التعديلات",
    ar_all_1060: "إجمالي الطلبات",
    ar_all_1061: "عناويني",
    ar_all_1062: "الإعدادات",
    ar_all_1063: "السياسة والخصوصية",
    ar_all_1064: "مشاوير دمنهور - أسرع دليفري وتتبع الطيار",
    ar_all_1065: "تطبيق مشاوير دمنهور - ريّح نفسك وتتبع طيارك دقيقة بدقيقة!",
    ar_all_1066: "تم نسخ رابط التطبيق بنجاح!",
    ar_all_1067: "مشاركة التطبيق",
    ar_all_1068: "أرقام الدعم الفني",
    ar_all_1069: "تسجيل الخروج",
    ar_all_1070: "تسجيل الخروج؟",
    ar_all_1071: "هل أنت متأكد أنك تريد الخروج من الحساب؟",
    ar_all_1072: "إلغاء",
    ar_all_1073: "خروج",
    ar_all_1074: "الإصدار 1.0.6 - نسخة مشتل كرم عاشور",
    ar_all_1075: "1. جمع المعلومات",
    ar_all_1076: "نحن نجمع المعلومات التي تقدمها لنا مباشرة عند التسجيل، مثل اسمك، رقم هاتفك، وعناوين التوصيل. كما نجمع بيانات الموقع الجغرافي لتسهيل عملية التوصيل.",
    ar_all_1077: "2. استخدام المعلومات",
    ar_all_1078: "نستخدم المعلومات لتقديم خدمات التوصيل، تحسين التطبيق، والتواصل معك بخصوص طلباتك. لن نشارك بياناتك مع أطراف ثالثة لأغراض تسويقية دون موافقتك.",
    ar_all_1079: "3. أمان البيانات",
    ar_all_1080: "نحن نتخذ تدابير أمنية مناسبة لحماية معلوماتك الشخصية من الوصول غير المصرح به أو التغيير أو الإفصاح أو الإتلاف.",
    ar_all_1081: "4. حقوق المستخدم",
    ar_all_1082: "لديك الحق في الوصول إلى بياناتك الشخصية، تصحيحها، أو طلب حذفها في أي وقت من خلال إعدادات التطبيق أو التواصل مع الدعم الفني.",
    ar_all_1083: "آخر تحديث: 25 أكتوبر 2023",
    ar_all_1084: "طلباتي",
    ar_all_1085: "ابحث برقم الطلب، العناصر، العنوان، أو السعر...",
    ar_all_1086: "الجارية (",
    ar_all_1087: "السابقة (",
    ar_all_1088: "لا توجد طلبات هنا",
    ar_all_1089: "مستهدف لك خصيصاً 🎯",
    ar_all_1090: "فرصة تجميع (Batch)",
    ar_all_1091: "تم نسخ الرقم",
    ar_all_1092: "تواصل مع",
    ar_all_1093: "مراسلة واتساب",
    ar_all_1094: "اتصال",
    ar_all_1095: "المرسل",
    ar_all_1096: "المستلم",
    ar_all_1097: "الراسل",
    ar_all_1098: "هل أنت متأكد من إلغاء الطلب نهائياً؟",
    ar_all_1099: "برجاء كتابة سبب الإلغاء",
    ar_all_1100: "تم إرسال طلب إلغاء الطلب للإدارة.\nسيتم التواصل معك أو مع الكابتن لتأكيد الإلغاء.",
    ar_all_1101: "إجمالي الحساب",
    ar_all_1102: "نوع الطلب",
    ar_all_1103: "رسوم التوصيل:",
    ar_all_1104: "مبلغ التحصيل (الكاش):",
    ar_all_1105: "من سيدفع التوصيل؟",
    ar_all_1106: "استلام من:",
    ar_all_1107: "افتح الخريطة",
    ar_all_1108: "توصيل إلى:",
    ar_all_1109: "تتبع العنوان",
    ar_all_1110: "العميل",
    ar_all_1111: "اتصال بـ",
    ar_all_1112: "شات داخلي",
    ar_all_1113: "تحدث الآن",
    ar_all_1114: "جاري تعيين طيار ⏳",
    ar_all_1115: "تم قبول الطلب والأوردر في مرحلة التجهيز 📦",
    ar_all_1116: "الطيار استلم الأوردر وجاري الانطلاق 🛵💨",
    ar_all_1117: "الطيار استلم الأوردر وهو في الطريق إليك الآن! 🛵💨",
    ar_all_1118: "تم تسليم الأوردر بنجاح! شكراً لتعاملك معنا ✅",
    ar_all_1119: "تم إلغاء الطلب ❌",
    ar_all_1120: "تم إرجاع الطلب للراسل 🔙",
    ar_all_1121: "تحديث الزبون بمكان الطيار على الواتساب 📲",
    ar_all_1122: "محتوى الطلب",
    ar_all_1123: "💡 ملاحظات:",
    ar_all_1124: "مرفقات الطلب",
    ar_all_1125: "رسالة صوتية للطلب",
    ar_all_1126: "إثبات التوصيل ✅",
    ar_all_1127: "تقييم ومؤشرات التوصيل",
    ar_all_1128: "مستغرق:",
    ar_all_1129: "دقيقة",
    ar_all_1130: "تقييم العميل للمندوب:",
    ar_all_1131: "اختر التقييم:",
    ar_all_1132: "اكتب كلمة شكر أو تعليقك على أداء المندوب وسلوكه (اختياري)...",
    ar_all_1133: "✅ شكراً لك! تم إرسال تقييمك بنجاح.",
    ar_all_1134: "❌ فشل إرسال التقييم، يرجى المحاولة لاحقاً.",
    ar_all_1135: "جاري الإرسال...",
    ar_all_1136: "إرسال التقييم للمندوب",
    ar_all_1137: "بانتظار تقييم العميل لهذا الطلب",
    ar_all_1138: "إغلاق تبليغ التأخير",
    ar_all_1139: "تبليغ عن تأخير (زحمة / عطل)",
    ar_all_1140: "اكتب سبب التأخير...",
    ar_all_1141: "إرسال",
    ar_all_1142: "إلغاء الطلب",
    ar_all_1143: "طلب إلغاء الرحلة",
    ar_all_1144: "تم الاستلام من الراسل",
    ar_all_1145: "تحركت للمستلم",
    ar_all_1146: "وصلت وسلمت (تصوير)",
    ar_all_1147: "قبول الطلب",
    ar_all_1148: "تتبع الكابتن",
    ar_all_1149: "إغلاق الصفحة",
    ar_all_1150: "اكتب السبب عشان الادارة توافق",
    ar_all_1151: "ايه السبب؟",
    ar_all_1152: "تراجع",
    ar_all_1153: "إرسال للأدمن",
    ar_all_1154: "الإشعارات",
    ar_all_1155: "جديد",
    ar_all_1156: "لا توجد إشعارات حالياً",
    ar_all_1157: "٠١٢٣٤٥٦٧٨٩",
    ar_all_1158: "جاري التحميل...",
    ar_all_1159: "أسرع شحن وتوصيل بدمنهور",
    ar_all_1160: "أنظمة توزيع ذكية وطيارون محترفون في خدمتك طوال الـ 24 ساعة لتوصيل طلباتك في دقائق.",
    ar_all_1161: "تتبع حي ومباشر على الخريطة",
    ar_all_1162: "شاهد موقع الكابتن خطوة بخطوة من لحظة انطلاقه وحتى وصوله لباب منزلك بدقة متناهية.",
    ar_all_1163: "أمان تام بضمان ذكي",
    ar_all_1164: "بروتوكولات حماية متطورة وتأكيد فوري عبر الأكواد لضمان تسليم الشحنات لأصحابها بأمان.",
    ar_all_1165: "خطأ في الدخول. تأكد من الرقم وكلمة المرور.",
    ar_all_1166: "حدث خطأ غير متوقع",
    ar_all_1167: "خطأ في تسجيل الدخول",
    ar_all_1168: "تم حظر النافذة المنبثقة من المتصفح. يرجى تفعيل النوافذ المنبثقة لحساب Google.",
    ar_all_1169: "فشل تسجيل الدخول بواسطة Google",
    ar_all_1170: "كلمة المرور يجب أن تكون 4 أرقام/حروف على الأقل",
    ar_all_1171: "كلمة المرور غير متطابقة",
    ar_all_1172: "خطأ في إنشاء الحساب",
    ar_all_1173: "حدث خطأ أثناء الإنشاء",
    ar_all_1174: "أكمل ملفك الشخصي",
    ar_all_1175: "خطوة واحدة بسيطة لبدء الاستمتاع بخدماتنا السريعة",
    ar_all_1176: "خطأ في إكمال التسجيل",
    ar_all_1177: "حدث خطأ أثناء إكمال الحساب",
    ar_all_1178: "الاسم كاملاً",
    ar_all_1179: "المنطقة السكنية",
    ar_all_1180: "اختر المنطقة السكنية",
    ar_all_1181: "الشارع، رقم العمارة، الطابق...",
    ar_all_1182: "أكمل التسجيل وابدأ الآن 🚀",
    ar_all_1183: "عالطاير",
    ar_all_1184: "منصة الخدمات اللوجستية الذكية بدمنهور",
    ar_all_1185: "سهّل عمليات الشحن",
    ar_all_1186: "مع لوحة",
    ar_all_1187: "تحكم عالطاير",
    ar_all_1188: "أسرع تطبيق دليفري وتوزيع ذكي يربط المتاجر والطيارين بدمنهور في واجهة تتبع حية وفورية.",
    ar_all_1189: "أمان تام",
    ar_all_1190: "تحديث لحظي",
    ar_all_1191: "تقييم 4.9",
    ar_all_1192: "العربية",
    ar_all_1193: "انضم إلينا",
    ar_all_1194: "مرحباً بعودتك",
    ar_all_1195: "سجل حسابك للتمتع بتوصيل ذكي ومضمون",
    ar_all_1196: "الرجاء تسجيل الدخول لحسابك",
    ar_all_1197: "كلمة المرور",
    ar_all_1198: "نسيت كلمة السر؟",
    ar_all_1199: "تسجيل الدخول",
    ar_all_1200: "الاسم بالكامل",
    ar_all_1201: "العنوان بالتفصيل",
    ar_all_1202: "كلمة المرور (٤ أرقام)",
    ar_all_1203: "تأكيد كلمة المرور",
    ar_all_1204: "إنشاء الحساب والبدء",
    ar_all_1205: "أو الدخول السريع عبر",
    ar_all_1206: "الدخول السريع بـ Google",
    ar_all_1207: "ليس لديك حساب؟ ",
    ar_all_1208: "إنشاء حساب جديد",
    ar_all_1209: "لديك حساب بالفعل؟ ",
    ar_all_1210: "تسجيل دخول",
    ar_all_1211: "نسخة تجريبية: تسجيل دخول ذكي سريع",
    ar_all_1212: "المدير 👑",
    ar_all_1213: "الموظف 💼",
    ar_all_1214: "الطيار 🛵",
    ar_all_1215: "العميل 👤",
    ar_all_1216: "تعذر الوصول إلى موقعك الحالي. تأكد من إعطاء الصلاحية.",
    ar_all_1217: "موقعي الحالي",
    ar_all_1218: "تحديد موقعي الحالي تلقائياً",
    ar_all_1219: "اسحب الدبوس لتحديد الموقع بدقة",
    ar_all_1220: "نشط",
    ar_all_1221: "متاح",
    ar_all_1222: "مشغول",
    ar_all_1223: "خامل",
    ar_all_1224: "طلب",
    ar_all_1225: "في هذه الدائرة",
    ar_all_1226: "مغلق",
    ar_all_1227: "⚠️ خامل منذ",
    ar_all_1228: "آخر إشارة:",
    ar_all_1229: "الآن",
    ar_all_1230: "مشغول (",
    ar_all_1231: ") طلب",
    ar_all_1232: "متاح للعمل",
    ar_all_1233: "المحادثات النشطة",
    ar_all_1234: "تواصل مع العملاء للطلبات الحالية",
    ar_all_1235: "لا توجد محادثات نشطة",
    ar_all_1236: "ابدأ رحلة لتفعيل المحادثة",
    ar_all_1237: "الميكروفون غير مدعوم أو غير متاح في هذا المتصفح.",
    ar_all_1238: "يرجى إعطاء صلاحية الميكروفون للمتصفح",
    ar_all_1239: "حجم الصورة كبير جداً (الأقصى 2MB)",
    ar_all_1240: "محادثة الرحلة",
    ar_all_1241: "لا توجد رسائل بعد",
    ar_all_1242: "ابدأ المحادثة الآن",
    ar_all_1243: "⏪ اسحب لليسار للإلغاء",
    ar_all_1244: "اكتب رسالة...",
    ar_all_1245: "يرجى إدخال عنوان ونص الإشعار",
    ar_all_1246: "لم يتم العثور على المستخدم",
    ar_all_1247: "حدث خطأ أثناء الإرسال",
    ar_all_1248: "إرسال إشعارات جماعية",
    ar_all_1249: "الفئة المستهدفة",
    ar_all_1250: "العملاء",
    ar_all_1251: "الكباتن",
    ar_all_1252: "مستخدم محدد",
    ar_all_1253: "اختر المستخدم",
    ar_all_1254: "-- اختر مستخدم --",
    ar_all_1255: "كابتن",
    ar_all_1256: "عميل",
    ar_all_1257: "عنوان الإشعار",
    ar_all_1258: "مثال: خصم جديد!",
    ar_all_1259: "نص الإشعار",
    ar_all_1260: "اكتب تفاصيل الرسالة هنا...",
    ar_all_1261: "إرسال الآن"
  },
  en: {
    // Nav
    home: "Home",
    orders: "My Orders",
    chats: "Chats",
    profile: "Profile",
    settings: "Settings",
    privacy: "Privacy Policy",
    addresses: "Saved Addresses",
    logOut: "Log Out",
    // Login screen
    welcomeTitle: "We missed you, hero! 👋",
    welcomeSubtitle: "Log in to start our day",
    joinTitle: "Join Meshaweer Damanhour ✨",
    joinSubtitle: "For the fastest delivery and tracking right to your doorstep",
    phoneLabel: "Phone Number",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    fullNameLabel: "Full Name",
    addressLabel: "Detailed Address",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    loginBtn: "Let's Go (Log In)",
    registerBtn: "Create New Account",
    noAccount: "Don't have an account?",
    registerHereNow: "Register here now",
    demoQuickLogin: "Demo Mode: Quick Entry",
    admin: "Admin 👑",
    captain: "Captain 🛵",
    customer: "Customer 👤",
    loading: "Loading...",
    // Settings Screen
    settingsTitle: "Settings",
    notifications: "Notifications",
    darkMode: "Dark Mode",
    sounds: "Sounds",
    language: "Language",
    reportIssue: "Report Technical Issue",
    changePassword: "Change Password",
    arabic: "العربية",
    english: "English",
    currentPassword: "Current Password",
    newPassword: "New Password",
    saveChanges: "Save Changes",
    sendReport: "Send Report",
    describeIssue: "Describe the issue you are facing in detail",
    writeHere: "Write here...",
    logoutConfirmTitle: "Log out?",
    logoutConfirmDesc: "Are you sure you want to log out of your account?",
    cancel: "Cancel",
    exit: "Log Out",
    // Double order / preferences
    allowDoubleOrder: "Allow double delivery with another captain?",
    allowDoubleOrderDescAccept: "✅ You allow the driver to carry another order on your route to save time and effort.",
    allowDoubleOrderDescReject: "🚫 Solo & Fast: The representative is completely prohibited from carrying any other order until yours is safely delivered.",
    allowDoubleOrderMerchant: "Allow the driver to carry an extra order with yours?",
    allowDoubleOrderMerchantAccept: "✅ Allowed: The driver can batch this with another nearby order on the way.",
    allowDoubleOrderMerchantReject: "🚫 Restricted (fast single shipment): The driver must work on this order specifically.",
    deliveryPreference: "Delivery Preference",
    allowedDoubleOrderBadge: "🔄 Batching Allowed",
    soloOrderBadge: "🔒 Solo Only",
    doubleOrderAllowedMsg: "🔄 Multi-order delivery allowed to save time",
    doubleOrderSoloMsg: "🔒 Solo & fast shipment: No bundling of other orders allowed",
    // General Words
    currency: "EGP",
    sendToCaptain: "Send to Captain",
    customerName: "Customer Name",
    deliveryCode: "Delivery Code",
    priceText: "Price",
    itemCost: "Item Cost",
    recipientPhone: "Recipient Phone",
    notes: "Notes",
    zone: "Zone",
    addAddress: "Add New Address",
    voiceNotes: "Voice Notes",
    successCode: "✅ Acceptance confirmed successfully!",
    errorCode: "❌ Wrong code or invalid order.",
    connectionError: "Connecting to database.. Please wait",
    technicalSupport: "Technical Support",
    support24: "We are here to help you 24/7",
    selectChannel: "Choose contact method",
    contactWA: "Contact via WhatsApp",
    contactCall: "Phone Call",
    statusText: "Status",
    newOrderAlert: "New Order Available! 📦",
    newOrderAlertBody: "A new order is available at {address}. Click to accept.",
    offlineAlert: "No internet connection! ⚠️",
    // Dashboard Details
    goodMorning: "Good morning! ✨",
    dashboard: "Dashboard",
    updatePasswordSuccess: "Password changed successfully",
    reportSentSuccess: "Your report has been received and support will review it.",
    currentBalance: "Current Balance",
    history: "History Log",
    activeOrders: "Active Orders",
    availableOrders: "Available Orders",
    addOrderBtn: "Create Order",
    myOrders: "My Orders",
    deliveryCost: "Delivery Cost",
    resetGuide: "Reset User Guide",
    geoError: "Geofence Error",
    connectionIssue: "Connection Issue",
    connectionErrorFull: "Database connection failed. Please ensure you have internet access.",
    refreshPage: "Refresh Page 🔄",
    contactSupport: "Contact Support 🎧",
    appName: "3alTayar",
    youAreOnline: "You are Online",
    youAreOffline: "You are Offline",
    ordersWillReachYou: "Orders will reach you immediately",
    clickToStart: "Click to start receiving orders",
    overallPerformance: "Overall Performance",
    details: "Details",
    totalOrders: "Total Orders",
    newOrdersTab: "New",
    activeOrdersTab: "Active",
    noOrdersNow: "No orders available currently",
    youAreOfflineStatus: "You are currently offline",
    changeStatusToReceive: "Change your status to Online to receive new orders",
    acceptOrderCode: "Enter Delivery Code",
    askCustomerForCode: "Ask the customer for the code to confirm",
    confirmDelivery: "Confirm Delivery",
    codeMissingError: "Please enter the code first",
    distanceCalcError: "Could not calculate distance",
    driverInfoMissing: "Driver information is incomplete",
    deliveryCompleted: "Order delivered successfully!",
    detailsMissing: "Details must be filled",
    recipientMissing: "Recipient name is required",
    finishDelivery: "Finish Delivery",
    ar_1: "0123456789",
    ar_3: "Light 🔥",
    ar_11: "Delete the region",
    ar_7: "Canceled",
    ar_9: "yesterday",
    ar_5: "complete",
    ar_8: "today",
    ar_16: "I am addicted",
    ar_10: "Name required",
    ar_12: "Are you sure you want to delete this area? This may affect older orders.",
    ar_17: "employee",
    ar_18: "captain",
    ar_19: "Add failed",
    ar_6: "My neighbor",
    ar_15: "Please fill out all the data",
    ar_4: "Medium ⚡",
    ar_13: "Yes, delete",
    ar_14: "to retreat",
    ar_20: "Approval to cancel the request",
    ar_2: "Quiet ❄️",
    ar_21: "Are you sure you want to agree to permanently cancel and return this order?",
    ar_23: "Cancellation request rejected",
    ar_35: "Map",
    ar_33: "unknown",
    ar_31: "Yes, block the user",
    ar_24: "Do you want to reject the cancellation request and keep the trip active with the representative?",
    ar_22: "Yes, he agreed to cancel",
    ar_29: "Block the user",
    ar_34: "Home",
    ar_39: "Analytics",
    ar_26: "User data has been updated successfully",
    ar_36: "Requests",
    ar_30: "Unblock",
    ar_28: "Unblock user",
    ar_38: "Customers",
    ar_40: "Finances",
    ar_37: "Captains",
    ar_25: "Yes, reject the cancellation request",
    ar_32: "Not specified",
    ar_27: "Update failed",
    ar_46: "Quick view 📊",
    ar_59: "Monthly revenue",
    ar_56: "Check out the site now",
    ar_58: "Updated in real time",
    ar_54: "Send notification 🔔",
    ar_43: "Notifications",
    ar_47: "Tracking map 🗺️",
    ar_50: "Member management 👥",
    ar_57: "Today's revenue",
    ar_48: "All orders 📦",
    ar_60: "From the beginning of this month",
    ar_49: "Our heroes 🏎️",
    ar_45: "Return to the main page",
    ar_51: "Our clients 👨‍👩‍👧‍👦",
    ar_44: "Settings",
    ar_52: "Financial reports 💰",
    ar_53: "Performance analysis 📈",
    ar_42: "administration",
    ar_55: "System settings ⚙️",
    ar_41: "Heat map",
    ar_72: "consent",
    ar_62: "Since the date of establishment",
    ar_61: "Grand total",
    ar_71: "the reason:",
    ar_69: "to request #",
    ar_64: "The delegate",
    ar_75: "He came in today",
    ar_76: "Total orders",
    ar_80: "Control panel",
    ar_68: "Cancellation requests are necessary! (",
    ar_74: "View full order details",
    ar_65: "month",
    ar_63: "Details of account income (representatives)",
    ar_66: "Total",
    ar_78: "Registered customer",
    ar_70: "You need approval",
    ar_79: "Quick system tools",
    ar_73: "to reject",
    ar_77: "Active pilot",
    ar_67: "There are no representatives currently registered",
    ar_97: "Mass alerts for phones",
    ar_82: "Track captains and orders",
    ar_90: "Customer list",
    ar_81: "Live map",
    ar_87: "Performance analysis",
    ar_100: "Search by name or number...",
    ar_86: "Track captains and their ratings",
    ar_99: "Add representatives, governorates, and pricing",
    ar_93: "Daily and monthly revenues",
    ar_92: "Financial reports",
    ar_89: "Places of concentration of requests",
    ar_83: "Create an order",
    ar_95: "Edit and block accounts",
    ar_91: "Customer data and addresses",
    ar_94: "Member management",
    ar_98: "System settings",
    ar_84: "Create an order for a customer",
    ar_88: "Captains performance and orders",
    ar_96: "Send a mass notification",
    ar_85: "Captains management",
    ar_110: "Register a new employee",
    ar_112: "The full name",
    ar_107: "Provincial shipping prices",
    ar_113: "Mobile number",
    ar_108: "Register a new captain",
    ar_105: "Add an employee",
    ar_102: "cancellation",
    ar_118: "Employee",
    ar_103: "Add captain",
    ar_115: "Adding...",
    ar_109: "Register a new administrator",
    ar_111: "the name",
    ar_116: "Captain",
    ar_101: "Save ✅",
    ar_117: "Admin",
    ar_104: "Add an admin",
    ar_120: "Example: Damanhour - Al-Zohour district",
    ar_114: "password",
    ar_119: "Name of the new region",
    ar_106: "Regional shipping rates",
    ar_134: "Shipping price",
    ar_122: "Round Trip",
    ar_130: "I'm going to come:",
    ar_123: "delivery",
    ar_128: "purchases:",
    ar_138: "The governorate price has been adjusted",
    ar_136: "The governorate has been added successfully",
    ar_121: "Purchases & Delivery",
    ar_140: "Search by order number, customer, store, or items...",
    ar_124: "The region has been added successfully",
    ar_129: "J.M",
    ar_131: "delivery:",
    ar_139: "Shipping price:",
    ar_127: "save",
    ar_132: "The name of the new governorate",
    ar_135: "Governorate name is required",
    ar_137: "Add the province to the shipping price",
    ar_133: "Example: Aswan",
    ar_126: "The region has been modified",
    ar_125: "Add the region with its prices",
    ar_144: "minute",
    ar_158: "Shows demand concentration areas based on the specified timescale to assist in the reallocation of pilots.",
    ar_141: "🟢 Available for work",
    ar_159: "List",
    ar_148: "Captain's order log",
    ar_155: "Area performance:",
    ar_156: "Excellent 🔥",
    ar_143: "evaluation)",
    ar_147: "There are no requests with him",
    ar_149: "Center",
    ar_152: "Total revenue",
    ar_142: "🔴 Not available",
    ar_145: "Successful request",
    ar_153: "Average time",
    ar_157: "Request density map (Heatmap)",
    ar_160: "High pressure",
    ar_150: "Production power",
    ar_146: "An order is being delivered now",
    ar_151: "Completed orders",
    ar_154: "D",
    ar_167: "There is no history of completed orders",
    ar_179: "Place name required",
    ar_172: "Microphone is not supported in this browser.",
    ar_175: "Please enter order details",
    ar_164: "There are no registered clients",
    ar_180: "Choose your primary address (reference)",
    ar_162: "There are no requests in this time range",
    ar_170: "Send to the captain via WhatsApp",
    ar_161: "middle",
    ar_165: "Titles",
    ar_163: "undefined",
    ar_176: "The sender",
    ar_173: "Please allow access to the microphone",
    ar_171: "Are you sure you want to cancel this order permanently?",
    ar_166: "Total collection",
    ar_169: "Let the captain scan the code or send it to him",
    ar_178: "Choose the delivery address",
    ar_168: "It was completed",
    ar_174: "Image size is too large (max. 5MB)",
    ar_177: "Recipient",
    ar_192: "My current location",
    ar_181: "Destination address is required",
    ar_190: "Fill in the data",
    ar_187: "Receiving a package",
    ar_196: "Add a new address",
    ar_194: "My addresses",
    ar_188: "Governorates Shipping",
    ar_193: "Location failed. Make sure GPS is turned on and allow the browser to access your location.",
    ar_182: "Package receiving address is required",
    ar_185: "Recipient number is required",
    ar_183: "Recipient address is required",
    ar_186: "Parcel Delivery",
    ar_189: "Recipient address (parcel)",
    ar_197: "Use my current location (GPS)",
    ar_184: "Recipient region is required",
    ar_195: "📍 GPS location",
    ar_200: "Title name",
    ar_191: "Your device does not support geolocation",
    ar_199: "Coordinates and address have been successfully determined",
    ar_198: "The address will be typed automatically",
    ar_214: "Trip details",
    ar_206: "Save this address",
    ar_210: "Write your request in detail here...",
    ar_201: "Example: home, office",
    ar_217: "Please select whether you want to send or receive a package",
    ar_211: "I'm going to come: The captain will take something from you, deliver it to a place, and return something else from there.",
    ar_215: "Example: He will take an order and return with money...",
    ar_220: "Receiving a package (I will receive a package from someone else) 📥",
    ar_218: "Parcel delivery (I sent a parcel to someone else) 📤",
    ar_203: "Address details (street, building...)",
    ar_205: "Manually modify the location on the map:",
    ar_208: "Example: KFC, El Ezaby Pharmacy",
    ar_204: "Write the detailed address here...",
    ar_207: "Name of the restaurant or shop (optional)",
    ar_212: "Destination (the place the captain is going to and coming back from)",
    ar_219: "I want the captain to come and receive a package from me and deliver it to someone else's address.",
    ar_213: "Example: Al Mahatta Street next to Al Bosta...",
    ar_209: "Accurately describe purchases",
    ar_216: "Choose the type of package service:",
    ar_202: "The region to which it belongs",
    ar_231: "Receiving address",
    ar_237: "Recipient's phone number",
    ar_233: "Sender's phone number",
    ar_236: "On where (recipient):",
    ar_225: "Receiving a package (I will get it)",
    ar_224: "Parcel delivery (Habat)",
    ar_222: "Sending from Damanhour to all governorates",
    ar_227: "Example: a bag of clothes, important papers...",
    ar_234: "Where is it (the place where the Indians were expelled):",
    ar_221: "I want the captain to go get a package from another place or person and deliver it to me at my place.",
    ar_238: "Recipient's governorate",
    ar_228: "From where (responder’s address - me):",
    ar_226: "Description of the shipment/package",
    ar_239: "Recipient area",
    ar_230: "Where is the sender from?",
    ar_240: "(for the price)",
    ar_235: "On VPN (recipient address - me):",
    ar_229: "From where (the place we will get the package):",
    ar_223: "Please choose your intended governorate below, and its shipping price will be determined automatically.",
    ar_232: "Street, building number, area...",
    ar_260: "Total:",
    ar_241: "Select the region",
    ar_252: "new",
    ar_258: "Delivery price:",
    ar_259: "Collection amount:",
    ar_245: "Request photo",
    ar_244: "Add additional details (optional)",
    ar_243: "Street, building number, floor...",
    ar_249: "Long press or single tap to start",
    ar_251: "On where (delivery address to you)",
    ar_257: "Who will pay the delivery costs?",
    ar_246: "Manual recording: Click again to save 💾",
    ar_253: "Please add a title first",
    ar_254: "Collection/payment of cash",
    ar_242: "Recipient's address in detail",
    ar_256: "Amount (excluding delivery)",
    ar_250: "Voice message to order",
    ar_247: "Or drag your finger to cancel",
    ar_248: "Register your voice request 🎤",
    ar_255: "Enable this option if the captain will pay an amount to the store or if he will collect an amount from the recipient.",
    ar_270: "2",
    ar_273: "3",
    ar_267: "1",
    ar_268: "Request your ride 📝",
    ar_271: "Choose the price and the pilot 🤝",
    ar_279: "Choose the request type",
    ar_274: "Live tracking and chat 🗺️",
    ar_262: "Confirm the order, champ 🚀",
    ar_261: "(Delivery will be paid by",
    ar_278: "What do you want to deliver? ✨",
    ar_277: "Got it, hide the evidence 🤝",
    ar_264: "💡 Quick usage guide",
    ar_280: "Purchases and delivery",
    ar_266: "Understand the Al Tayer system in 3 simple and excellent steps",
    ar_269: "Choose the service (food🛒, parcel📦, going to come🔄) and write your order. You can record a voice note or upload a picture to facilitate the explanation to the pilot!",
    ar_272: "Nearby representatives will compete for your order and suggest customized delivery rates. Compare their prices and ratings, and accept the best offer for you!",
    ar_276: "Ready to get started? Place your first order and experience the speed 🚀",
    ar_263: "Close the directory",
    ar_265: "How do you use the Al Tayyar application? 🛵",
    ar_275: "After acceptance, chat with the captain with excellent chat, track the representative’s itinerary live on the map, and deliver safely via QR code.",
    ar_296: "Code",
    ar_291: "the previous (",
    ar_281: "common",
    ar_288: "Your requests",
    ar_294: "the account",
    ar_295: "Chat",
    ar_299: "Please act now immediately to avoid sending an inactivity report to management.",
    ar_297: "Emergency Alert: The company has been notified!",
    ar_298: "Warning: You have been inactive for 10 minutes",
    ar_289: "Keep up to date with the status of your orders",
    ar_282: "Meals, grocery, pharmacy",
    ar_300: "Geographic error",
    ar_287: "From Damanhour to all governorates",
    ar_284: "A journey is coming",
    ar_285: "Deliver and come back with something",
    ar_286: "Shipping to the governorates of Egypt 🌎",
    ar_293: "Request an order now",
    ar_292: "There are no requests",
    ar_283: "From place to place",
    ar_290: "Current requests (",
    ar_314: "Overall rating:",
    ar_316: "unavailable",
    ar_313: "Performance evaluations",
    ar_311: "You are standing in your grocery store",
    ar_320: "Package and shipment details",
    ar_318: "Confirm delivery details",
    ar_306: "Phone number not available",
    ar_308: "You've been standing at your grocery store for a long time",
    ar_315: "There are no reviews recorded yet",
    ar_303: "The code is very short (6 numbers required)",
    ar_304: "This code is for another order entirely! See the code.",
    ar_301: "To finish the order, please enter the code received from the customer.",
    ar_302: "An error occurred while updating the order status",
    ar_319: "Please check the package and recipient before completing the order",
    ar_309: "minute). An inactivity alert was automatically sent to the company and management. Please act immediately to receive new orders.",
    ar_310: "Idle Warning: Please act now!",
    ar_307: "Emergency Alert: The company has been notified of your parking!",
    ar_312: "minutes. If you continue to park for 15 minutes, an emergency inactivity report will be sent to the company automatically!",
    ar_317: "Check and deliver",
    ar_305: "This code is not valid or the order has already been delivered",
    ar_327: "the address:",
    ar_333: "I completed",
    ar_337: "to update",
    ar_325: "Recipient and delivery data",
    ar_340: "Live tracking enabled",
    ar_321: "Order contents:",
    ar_332: "Edit code / return",
    ar_323: "Collection/package value:",
    ar_339: "The client is now following you",
    ar_324: "Who will pay the delivery?",
    ar_338: "Start working now",
    ar_326: "Recipient number:",
    ar_336: "slave girl (",
    ar_322: "Total account:",
    ar_335: "New (",
    ar_331: "Complete and confirm the delivery process",
    ar_334: "You have reached the limit (4 requests). Complete what you have to receive more.",
    ar_330: "✅ Correct code! The order has been successfully submitted and the details have been reviewed.",
    ar_328: "I have reviewed the contents of the package and matched the monetary value required for collection.",
    ar_329: "You have verified the current shipment recipient and their identity by matching recipient and customer data.",
    ar_348: "WhatsApp",
    ar_346: "Complete",
    ar_350: "details",
    ar_349: "communication",
    ar_343: "There is a picture",
    ar_347: "Chat",
    ar_345: "Enter the receipt code",
    ar_342: "If the order is cancelled, please contact the administration to find out whether the order will be completed or not",
    ar_341: "IMPORTANT ALERT!",
    ar_351: "Completed (4)",
    ar_344: "There is Voice Note",
    ctx_500: "Your account has been blocked. Please check with the administration.",
    ctx_501: "Database connection failed.",
    ctx_502: "Warning: long pause ⚠️",
    ctx_503: "Warning: A report has been sent 🚨",
    ctx_504: "Emergency idle alert 🚨",
    ctx_505: "Loss of GPS signal 📡",
    ctx_506: "Your request has been approved! ✅",
    ctx_507: "Order canceled 🚫",
    ctx_508: "New order available! 📦",
    ctx_509: "🚨 Urgent cancellation request!",
    ctx_510: "Your account has been blocked by the administration.",
    ctx_511: "New notification",
    ctx_512: "Connecting to the database. Please wait",
    ctx_513: "The number must be 11 digits",
    ctx_514: "The number is not registered or the password is wrong (or the account is blocked)",
    ctx_515: "Failed to connect to the server. Try again.",
    ctx_516: "Google login failed",
    ctx_517: "Failed to connect to the server",
    ctx_518: "Failed to complete registration",
    ctx_519: "The password is too short",
    ctx_520: "An error occurred",
    ctx_521: "User creation failed",
    ctx_522: "Failed to create request.",
    ctx_523: "Error connecting to the server",
    ctx_524: "⚠️ You cannot carry more than 4 orders at the same time.",
    ctx_525: "Sorry, another captain accepted the request seconds before you.",
    ctx_526: "Communication error",
    ctx_527: "Your order has been delivered 🎉",
    ctx_528: "You cannot confirm delivery of an order that is not assigned to you",
    ctx_529: "❌ The cancellation request was rejected by the administration and the delivery will be followed up.",
    ctx_530: "Captain",
    ctx_531: "Client",
    ctx_532: "The order has been canceled by management.",
    ctx_533: "⚠️ Your location cannot be determined. Make sure GPS is activated to confirm connection.",
    ctx_534: "Not logged in",
    ctx_535: "The new password is too short",
    ctx_536: "The password has been changed successfully",
    ctx_537: "Database update failed",
    ctx_538: "The amount is invalid",
    ctx_539: "Balance recharge failed",
    ctx_540: "Insufficient balance",
    ctx_541: "Balance withdrawal failed - check available balance",
    ctx_542: "Balance withdrawal failed",
    ctx_543: "🎤 Voice message",
    ctx_544: "📷 Image",
    ar_all_1001: "Current balance",
    ar_all_1011: "The delegate",
    ar_all_1000: "Wallet",
    ar_all_1007: "Latest operations",
    ar_all_1010: "Live tracking",
    ar_all_1012: "On the way to you",
    ar_all_1016: "Order details",
    ar_all_1013: "New order",
    ar_all_1006: "to be sure",
    ar_all_1018: "Delivery address",
    ar_all_1004: "Amount",
    ar_all_1014: "Customer name",
    ar_all_1002: "Recharge balance",
    ar_all_1017: "List of items...",
    ar_all_1008: "There are no recent operations",
    ar_all_1005: "Implementation in progress...",
    ar_all_1009: "The delegate arrives during",
    ar_all_1015: "Example: Ahmed Muhammad",
    ar_all_1003: "Withdraw a balance",
    ar_all_1019: "Street, building number, apartment",
    ar_all_1035: "in the way",
    ar_all_1027: "everyone",
    ar_all_1031: "Accepted",
    ar_all_1025: "Searching...",
    ar_all_1034: "It was received",
    ar_all_1020: "Area",
    ar_all_1030: "Waiting",
    ar_all_1028: "complete",
    ar_all_1032: "The bill has been paid",
    ar_all_1033: "In preparation",
    ar_all_1037: "Returned",
    ar_all_1029: "income",
    ar_all_1026: "Captain",
    ar_all_1038: "Canceled",
    ar_all_1036: "Delivered",
    ar_all_1024: "All orders are complete",
    ar_all_1022: "Search in store orders...",
    ar_all_1023: "Orders being delivered",
    ar_all_1021: "Send to the captain",
    ar_all_1039: "The reset was completed successfully. The guide will appear when you open the home page.",
    ar_all_1054: "The data has been updated successfully",
    ar_all_1040: "success",
    ar_all_1059: "Save modifications",
    ar_all_1048: "Upload a photo",
    ar_all_1056: "the name",
    ar_all_1053: "Name required",
    ar_all_1044: "Camera is not available",
    ar_all_1055: "Update failed. Try again.",
    ar_all_1051: "Contact via WhatsApp",
    ar_all_1052: "Phone call",
    ar_all_1057: "phone number",
    ar_all_1043: "Scan the receipt code",
    ar_all_1046: "Analyzing the image...",
    ar_all_1045: "Upload a photo instead",
    ar_all_1050: "Choose the means of communication",
    ar_all_1047: "Point the camera at the customer's QR code",
    ar_all_1042: "No valid QR code was found in the image. Try again more clearly.",
    ar_all_1049: "Scanning is automatic once you see the code",
    ar_all_1058: "To change the number, please contact support",
    ar_all_1041: "Unable to access the camera. Make sure to allow permissions or use image upload.",
    ar_all_1072: "cancellation",
    ar_all_1073: "exit",
    ar_all_1069: "Log out",
    ar_all_1075: "1. Collect information",
    ar_all_1061: "My addresses",
    ar_all_1060: "Total orders",
    ar_all_1067: "Share the app",
    ar_all_1062: "Settings",
    ar_all_1063: "Policy and privacy",
    ar_all_1068: "Technical support numbers",
    ar_all_1066: "The application link has been copied successfully!",
    ar_all_1079: "3. Data security",
    ar_all_1077: "2. Use of information",
    ar_all_1070: "Sign out?",
    ar_all_1071: "Are you sure you want to log out of the account?",
    ar_all_1065: "Damanhour Rides App - Relax yourself and follow your pilot minute by minute!",
    ar_all_1074: "Version 1.0.6 - Karam Ashour Nursery version",
    ar_all_1076: "We collect information that you provide directly to us when you register, such as your name, phone number, and delivery addresses. We also collect geographic location data to facilitate the delivery process.",
    ar_all_1078: "We use the information to provide delivery services, improve the App, and to communicate with you about your orders. We will not share your data with third parties for marketing purposes without your consent.",
    ar_all_1064: "Damanhour rides - fastest delivery and follow the pilot",
    ar_all_1094: "communication",
    ar_all_1081: "4. User rights",
    ar_all_1084: "My requests",
    ar_all_1095: "Sender",
    ar_all_1092: "Connect with",
    ar_all_1097: "The sender",
    ar_all_1096: "Recipient",
    ar_all_1093: "WhatsApp messaging",
    ar_all_1085: "Search by order number, items, title, or price...",
    ar_all_1098: "Are you sure to cancel the order permanently?",
    ar_all_1099: "Please write the reason for cancellation",
    ar_all_1083: "Last updated: October 25, 2023",
    ar_all_1090: "Batch opportunity",
    ar_all_1089: "Specially targeted for you 🎯",
    ar_all_1088: "There are no requests here",
    ar_all_1087: "Previous (",
    ar_all_1086: "slave girl (",
    ar_all_1091: "The number has been copied",
    ar_all_1080: "We take appropriate security measures to protect your personal information from unauthorized access, alteration, disclosure or destruction.",
    ar_all_1082: "You have the right to access, correct, or request deletion of your personal data at any time through the application settings or contacting technical support.",
    ar_all_1107: "Open the map",
    ar_all_1102: "Request type",
    ar_all_1105: "Who will pay the delivery?",
    ar_all_1109: "Tracking address",
    ar_all_1113: "Speak now",
    ar_all_1110: "Client",
    ar_all_1101: "Total account",
    ar_all_1104: "Collection amount (cash):",
    ar_all_1118: "The order was delivered successfully! Thank you for dealing with us ✅",
    ar_all_1119: "The order has been canceled ❌",
    ar_all_1114: "Pilot being recruited ⏳",
    ar_all_1100: "A request to cancel the order has been sent to the administration.\nYou or the captain will be contacted to confirm the cancellation.",
    ar_all_1116: "The pilot received the order and is launching 🛵💨",
    ar_all_1117: "Al-Tayyar received the order and is on its way to you now! 🛵💨",
    ar_all_1115: "The request has been accepted and the order is in the processing stage 📦",
    ar_all_1111: "Connect to",
    ar_all_1112: "Internal chat",
    ar_all_1108: "Delivery to:",
    ar_all_1106: "Receive from:",
    ar_all_1103: "Delivery fees:",
    ar_all_1128: "rapt:",
    ar_all_1122: "Request content",
    ar_all_1129: "minute",
    ar_all_1125: "Voice message to order",
    ar_all_1124: "Request attachments",
    ar_all_1135: "Sending...",
    ar_all_1139: "Report a delay (congestion/malfunction)",
    ar_all_1130: "Customer evaluation of the representative:",
    ar_all_1120: "The request has been returned to the sender 🔙",
    ar_all_1132: "Write a word of thanks or your comment on the delegate’s performance and behavior (optional)...",
    ar_all_1134: "❌ Failed to send rating, please try again later.",
    ar_all_1121: "Updating the customer with the pilot’s location on WhatsApp 📲",
    ar_all_1137: "Waiting for the customer to evaluate this order",
    ar_all_1126: "Proof of delivery ✅",
    ar_all_1138: "Close notification of delay",
    ar_all_1136: "Send the evaluation to the representative",
    ar_all_1127: "Evaluation and delivery indicators",
    ar_all_1123: "💡 Notes:",
    ar_all_1133: "✅ Thank you! Your review has been submitted successfully.",
    ar_all_1131: "Choose rating:",
    ar_all_1157: "0123456789",
    ar_all_1141: "send",
    ar_all_1155: "new",
    ar_all_1152: "to retreat",
    ar_all_1142: "Cancel order",
    ar_all_1156: "There are no notifications currently",
    ar_all_1158: "Loading...",
    ar_all_1154: "Notifications",
    ar_all_1150: "Write the reason so that the administration approves",
    ar_all_1149: "Close the page",
    ar_all_1151: "What is the reason?",
    ar_all_1148: "Follow the captain",
    ar_all_1159: "Fastest shipping and delivery in Damanhour",
    ar_all_1143: "Trip cancellation request",
    ar_all_1140: "Write the reason for the delay...",
    ar_all_1145: "Moved to the recipient",
    ar_all_1144: "Received from sender",
    ar_all_1146: "Arrived and delivered (photograph)",
    ar_all_1147: "Accept the request",
    ar_all_1153: "Send to admin",
    ar_all_1166: "An unexpected error occurred",
    ar_all_1174: "Complete your profile",
    ar_all_1167: "Error logging in",
    ar_all_1171: "Password mismatch",
    ar_all_1178: "Full name",
    ar_all_1169: "Sign in with Google failed",
    ar_all_1165: "Login error. Verify the number and password.",
    ar_all_1170: "Password must be at least 4 numbers/letters",
    ar_all_1168: "The pop-up window is blocked from the browser. Please enable pop-ups for your Google account.",
    ar_all_1175: "One simple step to start enjoying our fast services",
    ar_all_1172: "Error creating account",
    ar_all_1163: "Complete safety with smart guarantee",
    ar_all_1173: "An error occurred during creation",
    ar_all_1179: "Residential area",
    ar_all_1177: "An error occurred while completing the calculation",
    ar_all_1176: "Error completing registration",
    ar_all_1161: "Live tracking on the map",
    ar_all_1162: "Watch Captain's website step by step from the moment it is launched until it arrives at your door with utmost accuracy.",
    ar_all_1160: "Intelligent distribution systems and professional pilots are at your service 24 hours a day to deliver your orders in minutes.",
    ar_all_1164: "Advanced protection protocols and immediate confirmation via codes to ensure that shipments are delivered to their owners safely.",
    ar_all_1197: "password",
    ar_all_1181: "Street, building number, floor...",
    ar_all_1183: "On the fly",
    ar_all_1192: "Arabic",
    ar_all_1199: "Login",
    ar_all_1198: "Forgot your password?",
    ar_all_1190: "Real time update",
    ar_all_1191: "Rating 4.9",
    ar_all_1193: "join us",
    ar_all_1195: "Register your account to enjoy smart and secure delivery",
    ar_all_1196: "Please log in to your account",
    ar_all_1184: "Damanhour smart logistics services platform",
    ar_all_1180: "Select the residential area",
    ar_all_1194: "Welcome back",
    ar_all_1182: "Complete the registration and start now 🚀",
    ar_all_1185: "Make shipping easier",
    ar_all_1186: "With plate",
    ar_all_1187: "Control the fly",
    ar_all_1189: "Complete safety",
    ar_all_1188: "The fastest smart delivery and distribution application connects stores and pilots in Damanhour in a live and instant tracking interface.",
    ar_all_1217: "My current location",
    ar_all_1209: "Already have an account?",
    ar_all_1210: "Login",
    ar_all_1201: "Address in detail",
    ar_all_1203: "Confirm password",
    ar_all_1208: "Create a new account",
    ar_all_1200: "Full name",
    ar_all_1207: "Don't have an account?",
    ar_all_1218: "Automatically determine my current location",
    ar_all_1211: "Trial version: Fast smart login",
    ar_all_1219: "Drag the pin to pinpoint the exact location",
    ar_all_1214: "The pilot 🛵",
    ar_all_1215: "Client 👤",
    ar_all_1213: "Employee 💼",
    ar_all_1212: "Manager 👑",
    ar_all_1204: "Create an account and get started",
    ar_all_1202: "Password (4 numbers)",
    ar_all_1206: "Google Express Login",
    ar_all_1205: "Or express entry via",
    ar_all_1216: "Your current location cannot be reached. Make sure you give permission.",
    ar_all_1223: "idle",
    ar_all_1220: "active",
    ar_all_1224: "to request",
    ar_all_1225: "In this circle",
    ar_all_1231: ") to request",
    ar_all_1229: "now",
    ar_all_1222: "busy",
    ar_all_1233: "Active conversations",
    ar_all_1226: "closed",
    ar_all_1221: "available",
    ar_all_1232: "Available for work",
    ar_all_1238: "Please give your browser microphone access",
    ar_all_1234: "Contact customers for current orders",
    ar_all_1237: "Microphone is not supported or unavailable in this browser.",
    ar_all_1239: "Image size is too large (max. 2MB)",
    ar_all_1227: "⚠️ Inactive since",
    ar_all_1236: "Start a journey to spark conversation",
    ar_all_1235: "There are no active conversations",
    ar_all_1230: "busy (",
    ar_all_1228: "Last signal:",
    ar_all_1249: "Target group",
    ar_all_1250: "Customers",
    ar_all_1257: "Notice title",
    ar_all_1241: "No messages yet",
    ar_all_1244: "Write a message...",
    ar_all_1246: "User not found",
    ar_all_1251: "Captains",
    ar_all_1255: "captain",
    ar_all_1256: "client",
    ar_all_1248: "Send mass notifications",
    ar_all_1253: "Select user",
    ar_all_1242: "Start the conversation now",
    ar_all_1240: "Journey conversation",
    ar_all_1243: "⏪ Swipe left to cancel",
    ar_all_1258: "Example: New discount!",
    ar_all_1247: "An error occurred while sending",
    ar_all_1252: "Specific user",
    ar_all_1259: "Notice text",
    ar_all_1245: "Please enter the title and text of the notice",
    ar_all_1254: "--Select user--",
    ar_all_1261: "Submit now",
    ar_all_1260: "Write message details here..."
  }
};
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
export const LanguageProvider: React.FC<{
  children: React.ReactNode;
}> = ({
  children
}) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'en' || saved === 'ar') {
      return saved;
    }
    return 'ar';
  });
  const dir = language === 'ar' ? 'rtl' : 'ltr';
  const isAr = language === 'ar';
  const isEn = language === 'en';

  // Classes for layout alignments
  const alignLeft = isAr ? 'text-right' : 'text-left';
  const alignRight = isAr ? 'text-left' : 'text-right';
  useEffect(() => {
    localStorage.setItem('language', language);
    // Apply layout direction and language class dynamically on html element
    document.documentElement.setAttribute('dir', dir);
    document.documentElement.setAttribute('lang', language);
  }, [language, dir]);
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };
  const t = (key: TranslationKey | string, fallback?: string): string => {
    const langDict = translations[language];
    if (key in langDict) {
      return langDict[key as TranslationKey];
    }
    // Fallback to translations['ar'] or default fallback string
    const fallbackDict = translations['ar'];
    if (key in fallbackDict) {
      return fallbackDict[key as TranslationKey];
    }
    return fallback || key;
  };
  return <LanguageContext.Provider value={{
    language,
    setLanguage,
    t,
    dir,
    isAr,
    isEn,
    alignLeft,
    alignRight
  }}>
      <div dir={dir} className={isAr ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>;
};
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};